### job 配置项
jobs:
  agent:
    image: registry.erda.cloud/erda-actions/action-agent:1.6-alpha-20220120172436-d67ddd7e1
    labels:
      # 必填字段
      MD5: 451753deedc92f94486598bb99b4357b
    envs:
      # DEBUG mode, will produce more logs
      DEBUG: false
      # push log to collector
      ENABLE_PUSH_LOG_TO_COLLECTOR: false
      STDERR_REGEXP_LIST: '["^[a-z]*can*","^[a-z]*fail*"]'
      ENCRYPTED_VAlUE_MIN_LEN: 6
